---

version: "3.2"

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    restart: always

  wordpress:
    image: outlandish/bedrock
    environment:
      DB_HOST: db
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      WP_HOME: "http://localhost:8080"
      WP_ENV: development
    restart: always

  web:
    image: outlandish/bedrock-web
    ports:
      - 8080:80
      - 9432:9432
    environment:
      NGINX_PORT: 80
      NGINX_HOST: localhost:8080
      FPM_HOST: wordpress
      FPM_PORT: 9000
    restart: always